### ISSUE TITLE
stylegen errors do not lead to gulp failing properly

### ISSUE THREAD

**Issue by naltatis** [Galeria-Kaufhof/gulp-stylegen#1]
When a stylegen error occures gulp does not exit with `status 1`. The error only gets logged.

```
reading styleguide ...
writing styleguide ...
PlainComponentList.buildViewComponent /Users/[...]/view.hbs
{ [Error: The partial ev.partialName could not be found]
  description: undefined,
  ...
```

I think [PluginError](https://github.com/gulpjs/gulp-util#new-pluginerrorpluginname-message-options) could be helpful here.
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md (see 6. & 7.)

**Comment by mechanoid** [comment]
@naltatis please recheck and reopen if necessary! :)
